//
// Generated file, do not edit! Created by nedtool 5.7 from simulator/baseMessage.msg.
//

#ifndef __BASEMESSAGE_M_H
#define __BASEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <vector>
    #include "messages.h"

	inline std::ostream & operator << (std::ostream & os, const std::string & s) {
        std::operator<<(os, s);        
        return os;
	}
	typedef std::vector<std::string> stringVector;
// }}

/**
 * Class generated from <tt>simulator/baseMessage.msg:14</tt> by nedtool.
 * <pre>
 * packet BaseMessage
 * {
 *     string destination;
 *     int messageType;
 *     int hopCount;
 *     stringVector hops;
 *     //bool upstreamDirection;
 *     string displayString = "b=0,0,rect,o=white,white,0	";
 * }
 * </pre>
 */
class BaseMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string destination;
    int messageType;
    int hopCount;
    stringVector hops;
    ::omnetpp::opp_string displayString;

  private:
    void copy(const BaseMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BaseMessage&);

  public:
    BaseMessage(const char *name=nullptr, short kind=0);
    BaseMessage(const BaseMessage& other);
    virtual ~BaseMessage();
    BaseMessage& operator=(const BaseMessage& other);
    virtual BaseMessage *dup() const override {return new BaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
    virtual int getMessageType() const;
    virtual void setMessageType(int messageType);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual stringVector& getHops();
    virtual const stringVector& getHops() const {return const_cast<BaseMessage*>(this)->getHops();}
    virtual void setHops(const stringVector& hops);
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BaseMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BASEMESSAGE_M_H

