//
// Generated file, do not edit! Created by nedtool 5.7 from failHTLC.msg.
//

#ifndef __FAILHTLC_M_H
#define __FAILHTLC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>failHTLC.msg:1</tt> by nedtool.
 * <pre>
 * packet FailHTLC
 * {
 *     string errorReason;
 * }
 * </pre>
 */
class FailHTLC : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string errorReason;

  private:
    void copy(const FailHTLC& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FailHTLC&);

  public:
    FailHTLC(const char *name=nullptr, short kind=0);
    FailHTLC(const FailHTLC& other);
    virtual ~FailHTLC();
    FailHTLC& operator=(const FailHTLC& other);
    virtual FailHTLC *dup() const override {return new FailHTLC(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getErrorReason() const;
    virtual void setErrorReason(const char * errorReason);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FailHTLC& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FailHTLC& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FAILHTLC_M_H

