//
// Generated file, do not edit! Created by opp_msgtool 6.0 from invoice.msg.
//

#ifndef __INVOICE_M_H
#define __INVOICE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Invoice;
// cplusplus {{
    #include "messages.h"
// }}

/**
 * Class generated from <tt>invoice.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet Invoice
 * {
 *     string source;
 *     string destination;
 *     double value;
 *     string paymentHash;
 * }
 * </pre>
 */
class Invoice : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string source;
    omnetpp::opp_string destination;
    double value = 0;
    omnetpp::opp_string paymentHash;

  private:
    void copy(const Invoice& other);

  protected:
    bool operator==(const Invoice&) = delete;

  public:
    Invoice(const char *name=nullptr, short kind=0);
    Invoice(const Invoice& other);
    virtual ~Invoice();
    Invoice& operator=(const Invoice& other);
    virtual Invoice *dup() const override {return new Invoice(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSource() const;
    virtual void setSource(const char * source);

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);

    virtual double getValue() const;
    virtual void setValue(double value);

    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Invoice& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Invoice& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Invoice *fromAnyPtr(any_ptr ptr) { return check_and_cast<Invoice*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INVOICE_M_H

