//
// Generated file, do not edit! Created by nedtool 5.7 from invoice.msg.
//

#ifndef __INVOICE_M_H
#define __INVOICE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "messages.h"
// }}

/**
 * Class generated from <tt>invoice.msg:5</tt> by nedtool.
 * <pre>
 * packet Invoice
 * {
 *     string source;
 *     string destination;
 *     double value;
 *     string paymentHash;
 * }
 * </pre>
 */
class Invoice : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string source;
    ::omnetpp::opp_string destination;
    double value;
    ::omnetpp::opp_string paymentHash;

  private:
    void copy(const Invoice& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Invoice&);

  public:
    Invoice(const char *name=nullptr, short kind=0);
    Invoice(const Invoice& other);
    virtual ~Invoice();
    Invoice& operator=(const Invoice& other);
    virtual Invoice *dup() const override {return new Invoice(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
    virtual double getValue() const;
    virtual void setValue(double value);
    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Invoice& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Invoice& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INVOICE_M_H

