//
// Generated file, do not edit! Created by opp_msgtool 6.0 from payment.msg.
//

#ifndef __PAYMENT_M_H
#define __PAYMENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Payment;
// cplusplus {{
#include "globals.h"
// }}

/**
 * Class generated from <tt>payment.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet Payment
 * {
 *     string source;
 *     string destination;
 *     int hopCount = 0;
 *     double value;
 * }
 * </pre>
 */
class Payment : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string source;
    omnetpp::opp_string destination;
    int hopCount = 0;
    double value = 0;

  private:
    void copy(const Payment& other);

  protected:
    bool operator==(const Payment&) = delete;

  public:
    Payment(const char *name=nullptr, short kind=0);
    Payment(const Payment& other);
    virtual ~Payment();
    Payment& operator=(const Payment& other);
    virtual Payment *dup() const override {return new Payment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSource() const;
    virtual void setSource(const char * source);

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getValue() const;
    virtual void setValue(double value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Payment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Payment& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Payment *fromAnyPtr(any_ptr ptr) { return check_and_cast<Payment*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PAYMENT_M_H

