//
// Generated file, do not edit! Created by nedtool 5.7 from paymentRefused.msg.
//

#ifndef __PAYMENTREFUSED_M_H
#define __PAYMENTREFUSED_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <string>
    #include "messages.h"
// }}

/**
 * Class generated from <tt>paymentRefused.msg:6</tt> by nedtool.
 * <pre>
 * packet PaymentRefused
 * {
 *     string paymentHash;
 *     string errorReason;
 *     double value;
 * }
 * </pre>
 */
class PaymentRefused : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string paymentHash;
    ::omnetpp::opp_string errorReason;
    double value;

  private:
    void copy(const PaymentRefused& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PaymentRefused&);

  public:
    PaymentRefused(const char *name=nullptr, short kind=0);
    PaymentRefused(const PaymentRefused& other);
    virtual ~PaymentRefused();
    PaymentRefused& operator=(const PaymentRefused& other);
    virtual PaymentRefused *dup() const override {return new PaymentRefused(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
    virtual const char * getErrorReason() const;
    virtual void setErrorReason(const char * errorReason);
    virtual double getValue() const;
    virtual void setValue(double value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PaymentRefused& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PaymentRefused& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PAYMENTREFUSED_M_H

