//
// Generated file, do not edit! Created by nedtool 5.7 from revokeAndAck.msg.
//

#ifndef __REVOKEANDACK_M_H
#define __REVOKEANDACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <vector>
    #include "HTLC.h"
    
    typedef std::vector<HTLC *> HTLCVector;
// }}

/**
 * Class generated from <tt>revokeAndAck.msg:25</tt> by nedtool.
 * <pre>
 * packet revokeAndAck
 * {
 *     HTLCVector HTLCs;
 *     int ackId;
 * }
 * </pre>
 */
class revokeAndAck : public ::omnetpp::cPacket
{
  protected:
    HTLCVector HTLCs;
    int ackId;

  private:
    void copy(const revokeAndAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const revokeAndAck&);

  public:
    revokeAndAck(const char *name=nullptr, short kind=0);
    revokeAndAck(const revokeAndAck& other);
    virtual ~revokeAndAck();
    revokeAndAck& operator=(const revokeAndAck& other);
    virtual revokeAndAck *dup() const override {return new revokeAndAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual HTLCVector& getHTLCs();
    virtual const HTLCVector& getHTLCs() const {return const_cast<revokeAndAck*>(this)->getHTLCs();}
    virtual void setHTLCs(const HTLCVector& HTLCs);
    virtual int getAckId() const;
    virtual void setAckId(int ackId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const revokeAndAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, revokeAndAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __REVOKEANDACK_M_H

