//
// Generated file, do not edit! Created by nedtool 5.7 from updateFailHTLC.msg.
//

#ifndef __UPDATEFAILHTLC_M_H
#define __UPDATEFAILHTLC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <string>
    #include "messages.h"
// }}

/**
 * Class generated from <tt>updateFailHTLC.msg:6</tt> by nedtool.
 * <pre>
 * packet UpdateFailHTLC
 * {
 *     string paymentHash;
 * }
 * </pre>
 */
class UpdateFailHTLC : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string paymentHash;

  private:
    void copy(const UpdateFailHTLC& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateFailHTLC&);

  public:
    UpdateFailHTLC(const char *name=nullptr, short kind=0);
    UpdateFailHTLC(const UpdateFailHTLC& other);
    virtual ~UpdateFailHTLC();
    UpdateFailHTLC& operator=(const UpdateFailHTLC& other);
    virtual UpdateFailHTLC *dup() const override {return new UpdateFailHTLC(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdateFailHTLC& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdateFailHTLC& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEFAILHTLC_M_H

