//
// Generated file, do not edit! Created by nedtool 5.7 from simulator/updateFulfillHTLC.msg.
//

#ifndef __UPDATEFULFILLHTLC_M_H
#define __UPDATEFULFILLHTLC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <string>
    #include "messages.h"
// }}

/**
 * Class generated from <tt>simulator/updateFulfillHTLC.msg:6</tt> by nedtool.
 * <pre>
 * packet UpdateFulfillHTLC
 * {
 *     string paymentHash;
 *     string preImage;
 *     double value;
 * }
 * </pre>
 */
class UpdateFulfillHTLC : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string paymentHash;
    ::omnetpp::opp_string preImage;
    double value;

  private:
    void copy(const UpdateFulfillHTLC& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UpdateFulfillHTLC&);

  public:
    UpdateFulfillHTLC(const char *name=nullptr, short kind=0);
    UpdateFulfillHTLC(const UpdateFulfillHTLC& other);
    virtual ~UpdateFulfillHTLC();
    UpdateFulfillHTLC& operator=(const UpdateFulfillHTLC& other);
    virtual UpdateFulfillHTLC *dup() const override {return new UpdateFulfillHTLC(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
    virtual const char * getPreImage() const;
    virtual void setPreImage(const char * preImage);
    virtual double getValue() const;
    virtual void setValue(double value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UpdateFulfillHTLC& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UpdateFulfillHTLC& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEFULFILLHTLC_M_H

