//
// Generated file, do not edit! Created by nedtool 5.7 from transaction.msg.
//

#ifndef __TRANSACTION_M_H
#define __TRANSACTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>transaction.msg:2</tt> by nedtool.
 * <pre>
 * message Transaction
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 *     double value;
 * }
 * </pre>
 */
class Transaction : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int hopCount;
    double value;

  private:
    void copy(const Transaction& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Transaction&);

  public:
    Transaction(const char *name=nullptr, short kind=0);
    Transaction(const Transaction& other);
    virtual ~Transaction();
    Transaction& operator=(const Transaction& other);
    virtual Transaction *dup() const override {return new Transaction(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual double getValue() const;
    virtual void setValue(double value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Transaction& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Transaction& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSACTION_M_H

