//
// Generated file, do not edit! Created by nedtool 5.7 from updateAddHTLC.msg.
//

#ifndef __UPDATEADDHTLC_M_H
#define __UPDATEADDHTLC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include <string>
    #include "messages.h"
// }}

/**
 * Class generated from <tt>updateAddHTLC.msg:7</tt> by nedtool.
 * <pre>
 * packet update_add_htlc
 * {
 *     int source;
 *     string paymentHash;
 *     //simtime_t timeout; 
 *     double amount;
 * }
 * </pre>
 */
class update_add_htlc : public ::omnetpp::cPacket
{
  protected:
    int source;
    ::omnetpp::opp_string paymentHash;
    double amount;

  private:
    void copy(const update_add_htlc& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const update_add_htlc&);

  public:
    update_add_htlc(const char *name=nullptr, short kind=0);
    update_add_htlc(const update_add_htlc& other);
    virtual ~update_add_htlc();
    update_add_htlc& operator=(const update_add_htlc& other);
    virtual update_add_htlc *dup() const override {return new update_add_htlc(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual const char * getPaymentHash() const;
    virtual void setPaymentHash(const char * paymentHash);
    virtual double getAmount() const;
    virtual void setAmount(double amount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const update_add_htlc& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, update_add_htlc& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATEADDHTLC_M_H

